apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.shipment.plan
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 3
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: reefer.telemetries
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.inventory
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.transportation
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.reefer
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.reeferalerts
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.public.orderevents
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 3
  replicas: 3